import {
  FiCode,
  FiBriefcase,
  FiPenTool,
  FiHeart,
  FiBookOpen,
  FiCamera,
  FiMusic,
  FiGlobe,
  FiCpu,
  FiDollarSign,
  FiUsers,
  FiStar,
  FiFilm,
  FiActivity,
  FiShoppingBag,
  FiHome,
  FiCoffee,
  FiTrello,
  FiAnchor,
  FiAward,
} from 'react-icons/fi';
import { type IconType } from 'react-icons/lib';

// Key-based definition (type-safe & dynamic)
export const focusOptionMap = {
  tech: { label: 'Tech', icon: FiCode },
  business: { label: 'Business', icon: FiBriefcase },
  design: { label: 'Design', icon: FiPenTool },
  wellness: { label: 'Wellness', icon: FiHeart },
  education: { label: 'Education', icon: FiBookOpen },
  photography: { label: 'Photography', icon: FiCamera },
  music: { label: 'Music', icon: FiMusic },
  travel: { label: 'Travel', icon: FiGlobe },
  engineering: { label: 'Engineering', icon: FiCpu },
  finance: { label: 'Finance', icon: FiDollarSign },
  community: { label: 'Community', icon: FiUsers },
  creativity: { label: 'Creativity', icon: FiStar },
  film: { label: 'Film & Video', icon: FiFilm },
  fitness: { label: 'Fitness', icon: FiActivity },
  fashion: { label: 'Fashion', icon: FiShoppingBag },
  realestate: { label: 'Real Estate', icon: FiHome },
  food: { label: 'Food & Cooking', icon: FiCoffee },
  productivity: { label: 'Productivity', icon: FiTrello },
  sports: { label: 'Sports', icon: FiAnchor },
  science: { label: 'Science', icon: FiAward },
} as const;

export type AreaOfFocus = keyof typeof focusOptionMap;
export type TagType = 'goal' | 'interest' | 'skill';

export interface FocusOption {
  label: string;
  icon: IconType;
}

export interface FocusTag {
  label: string;
  type: TagType;
}

// Get full list as array (if needed)
export const goalsFocusOptions: (FocusOption & { value: AreaOfFocus })[] = Object.entries(focusOptionMap).map(
  ([value, { label, icon }]) => ({
    value: value as AreaOfFocus,
    label,
    icon,
  })
);

// Unified goals + interests + skill suggestions per focus area (5 goals, 5 interests, 5 skills each)
export const focusDetailsMap: Record<AreaOfFocus, FocusTag[]> = {
  tech: [
    { label: 'Learn to code', type: 'goal' },
    { label: 'Build a tech portfolio', type: 'goal' },
    { label: 'Get a tech internship', type: 'goal' },
    { label: 'Master a framework', type: 'goal' },
    { label: 'Contribute to open source', type: 'goal' },
    { label: 'Hackathons', type: 'interest' },
    { label: 'Tech podcasts', type: 'interest' },
    { label: 'Developer conferences', type: 'interest' },
    { label: 'Coding challenges', type: 'interest' },
    { label: 'Tech meetups', type: 'interest' },
    { label: 'JavaScript', type: 'skill' },
    { label: 'Python', type: 'skill' },
    { label: 'React', type: 'skill' },
    { label: 'Git', type: 'skill' },
    { label: 'API Development', type: 'skill' },
  ],
  business: [
    { label: 'Start a business', type: 'goal' },
    { label: 'Build a pitch deck', type: 'goal' },
    { label: 'Find co-founders', type: 'goal' },
    { label: 'Learn marketing basics', type: 'goal' },
    { label: 'Secure funding', type: 'goal' },
    { label: 'Business books', type: 'interest' },
    { label: 'Startup news', type: 'interest' },
    { label: 'Networking events', type: 'interest' },
    { label: 'Case studies', type: 'interest' },
    { label: 'Industry reports', type: 'interest' },
    { label: 'Strategic Planning', type: 'skill' },
    { label: 'Market Analysis', type: 'skill' },
    { label: 'Financial Modeling', type: 'skill' },
    { label: 'Negotiation', type: 'skill' },
    { label: 'Leadership', type: 'skill' },
  ],
  design: [
    { label: 'Master Figma', type: 'goal' },
    { label: 'Create a case study', type: 'goal' },
    { label: 'Redesign a product', type: 'goal' },
    { label: 'Build a portfolio', type: 'goal' },
    { label: 'Learn prototyping', type: 'goal' },
    { label: 'UI inspiration', type: 'interest' },
    { label: 'Design blogs', type: 'interest' },
    { label: 'Design communities', type: 'interest' },
    { label: 'Design sprints', type: 'interest' },
    { label: 'Creative workshops', type: 'interest' },
    { label: 'UI/UX Design', type: 'skill' },
    { label: 'Typography', type: 'skill' },
    { label: 'Color Theory', type: 'skill' },
    { label: 'Wireframing', type: 'skill' },
    { label: 'Prototyping', type: 'skill' },
  ],
  wellness: [
    { label: 'Improve work-life balance', type: 'goal' },
    { label: 'Practice mindfulness', type: 'goal' },
    { label: 'Start journaling', type: 'goal' },
    { label: 'Establish sleep routine', type: 'goal' },
    { label: 'Reduce stress levels', type: 'goal' },
    { label: 'Yoga classes', type: 'interest' },
    { label: 'Meditation groups', type: 'interest' },
    { label: 'Wellness retreats', type: 'interest' },
    { label: 'Health podcasts', type: 'interest' },
    { label: 'Nature walks', type: 'interest' },
    { label: 'Stress Management', type: 'skill' },
    { label: 'Mindfulness', type: 'skill' },
    { label: 'Nutrition Planning', type: 'skill' },
    { label: 'Yoga Instruction', type: 'skill' },
    { label: 'Breathing Techniques', type: 'skill' },
  ],
  education: [
    { label: 'Finish a course', type: 'goal' },
    { label: 'Improve study habits', type: 'goal' },
    { label: 'Start a blog', type: 'goal' },
    { label: 'Learn a new language', type: 'goal' },
    { label: 'Get certified', type: 'goal' },
    { label: 'Online lectures', type: 'interest' },
    { label: 'Book clubs', type: 'interest' },
    { label: 'Educational podcasts', type: 'interest' },
    { label: 'Study groups', type: 'interest' },
    { label: 'Academic conferences', type: 'interest' },
    { label: 'Curriculum Development', type: 'skill' },
    { label: 'Lesson Planning', type: 'skill' },
    { label: 'Public Speaking', type: 'skill' },
    { label: 'Research Methods', type: 'skill' },
    { label: 'Tutoring', type: 'skill' },
  ],
  photography: [
    { label: 'Build a photo portfolio', type: 'goal' },
    { label: 'Learn editing', type: 'goal' },
    { label: 'Shoot 30 days straight', type: 'goal' },
    { label: 'Master manual mode', type: 'goal' },
    { label: 'Exhibit work publicly', type: 'goal' },
    { label: 'Photo walks', type: 'interest' },
    { label: 'Photography contests', type: 'interest' },
    { label: 'Camera gear reviews', type: 'interest' },
    { label: 'Photo exhibitions', type: 'interest' },
    { label: 'Travel photography', type: 'interest' },
    { label: 'Composition', type: 'skill' },
    { label: 'Lighting Techniques', type: 'skill' },
    { label: 'Photo Editing', type: 'skill' },
    { label: 'Portrait Photography', type: 'skill' },
    { label: 'Landscape Photography', type: 'skill' },
  ],
  music: [
    { label: 'Release a track', type: 'goal' },
    { label: 'Learn music production', type: 'goal' },
    { label: 'Join a music group', type: 'goal' },
    { label: 'Master an instrument', type: 'goal' },
    { label: 'Perform live', type: 'goal' },
    { label: 'Music festivals', type: 'interest' },
    { label: 'Jam sessions', type: 'interest' },
    { label: 'Music theory classes', type: 'interest' },
    { label: 'Album reviews', type: 'interest' },
    { label: 'Concert going', type: 'interest' },
    { label: 'Music Theory', type: 'skill' },
    { label: 'Instrument Proficiency', type: 'skill' },
    { label: 'Audio Production', type: 'skill' },
    { label: 'Songwriting', type: 'skill' },
    { label: 'Ear Training', type: 'skill' },
  ],
  travel: [
    { label: 'Plan a cultural trip', type: 'goal' },
    { label: 'Document my travels', type: 'goal' },
    { label: 'Work remotely abroad', type: 'goal' },
    { label: 'Visit 5 new countries', type: 'goal' },
    { label: 'Learn local customs', type: 'goal' },
    { label: 'Travel blogs', type: 'interest' },
    { label: 'Backpacking groups', type: 'interest' },
    { label: 'Adventure sports', type: 'interest' },
    { label: 'Cultural festivals', type: 'interest' },
    { label: 'Local cuisine', type: 'interest' },
    { label: 'Trip Planning', type: 'skill' },
    { label: 'Budget Management', type: 'skill' },
    { label: 'Cultural Awareness', type: 'skill' },
    { label: 'Language Basics', type: 'skill' },
    { label: 'Travel Photography', type: 'skill' },
  ],
  engineering: [
    { label: 'Build a side project', type: 'goal' },
    { label: 'Contribute to open source', type: 'goal' },
    { label: 'Strengthen problem-solving', type: 'goal' },
    { label: 'Get engineering certification', type: 'goal' },
    { label: 'Design a prototype', type: 'goal' },
    { label: 'Tech meetups', type: 'interest' },
    { label: 'Engineering podcasts', type: 'interest' },
    { label: 'Maker spaces', type: 'interest' },
    { label: 'Technical workshops', type: 'interest' },
    { label: 'Industry conferences', type: 'interest' },
    { label: 'CAD Design', type: 'skill' },
    { label: 'Structural Analysis', type: 'skill' },
    { label: 'Project Management', type: 'skill' },
    { label: 'Technical Drawing', type: 'skill' },
    { label: 'Systems Engineering', type: 'skill' },
  ],
  finance: [
    { label: 'Start budgeting', type: 'goal' },
    { label: 'Track expenses', type: 'goal' },
    { label: 'Build an emergency fund', type: 'goal' },
    { label: 'Invest in stocks', type: 'goal' },
    { label: 'Plan for retirement', type: 'goal' },
    { label: 'Personal finance blogs', type: 'interest' },
    { label: 'Investment clubs', type: 'interest' },
    { label: 'Financial news', type: 'interest' },
    { label: 'Economic trends', type: 'interest' },
    { label: 'Wealth building', type: 'interest' },
    { label: 'Financial Analysis', type: 'skill' },
    { label: 'Investment Strategies', type: 'skill' },
    { label: 'Risk Management', type: 'skill' },
    { label: 'Tax Planning', type: 'skill' },
    { label: 'Portfolio Management', type: 'skill' },
  ],
  community: [
    { label: 'Host a local event', type: 'goal' },
    { label: 'Volunteer weekly', type: 'goal' },
    { label: 'Start a community group', type: 'goal' },
    { label: 'Organize a fundraiser', type: 'goal' },
    { label: 'Mentor someone', type: 'goal' },
    { label: 'Community projects', type: 'interest' },
    { label: 'Local meetups', type: 'interest' },
    { label: 'Social causes', type: 'interest' },
    { label: 'Neighborhood events', type: 'interest' },
    { label: 'Civic engagement', type: 'interest' },
    { label: 'Event Planning', type: 'skill' },
    { label: 'Public Relations', type: 'skill' },
    { label: 'Community Outreach', type: 'skill' },
    { label: 'Conflict Resolution', type: 'skill' },
    { label: 'Volunteer Coordination', type: 'skill' },
  ],
  creativity: [
    { label: 'Do a 30-day challenge', type: 'goal' },
    { label: 'Start a creative habit', type: 'goal' },
    { label: 'Share my work online', type: 'goal' },
    { label: 'Complete a major project', type: 'goal' },
    { label: 'Collaborate with artists', type: 'goal' },
    { label: 'Creative workshops', type: 'interest' },
    { label: 'Art exhibitions', type: 'interest' },
    { label: 'Maker communities', type: 'interest' },
    { label: 'Creative writing groups', type: 'interest' },
    { label: 'Art supply stores', type: 'interest' },
    { label: 'Creative Writing', type: 'skill' },
    { label: 'Drawing', type: 'skill' },
    { label: 'Painting', type: 'skill' },
    { label: 'Sculpture', type: 'skill' },
    { label: 'Digital Art', type: 'skill' },
  ],
  film: [
    { label: 'Create a short film', type: 'goal' },
    { label: 'Learn video editing', type: 'goal' },
    { label: 'Build a film portfolio', type: 'goal' },
    { label: 'Enter a film festival', type: 'goal' },
    { label: 'Master camera techniques', type: 'goal' },
    { label: 'Film festivals', type: 'interest' },
    { label: 'Director commentaries', type: 'interest' },
    { label: 'Cinematography blogs', type: 'interest' },
    { label: 'Movie marathons', type: 'interest' },
    { label: 'Behind-the-scenes content', type: 'interest' },
    { label: 'Video Editing', type: 'skill' },
    { label: 'Storyboarding', type: 'skill' },
    { label: 'Cinematography', type: 'skill' },
    { label: 'Screenwriting', type: 'skill' },
    { label: 'Sound Design', type: 'skill' },
  ],
  fitness: [
    { label: 'Run a marathon', type: 'goal' },
    { label: 'Build a workout routine', type: 'goal' },
    { label: 'Achieve fitness milestone', type: 'goal' },
    { label: 'Learn proper form', type: 'goal' },
    { label: 'Track progress consistently', type: 'goal' },
    { label: 'Fitness challenges', type: 'interest' },
    { label: 'Gym communities', type: 'interest' },
    { label: 'Sports nutrition', type: 'interest' },
    { label: 'Workout apps', type: 'interest' },
    { label: 'Fitness influencers', type: 'interest' },
    { label: 'Personal Training', type: 'skill' },
    { label: 'Nutrition Planning', type: 'skill' },
    { label: 'Exercise Form', type: 'skill' },
    { label: 'Workout Programming', type: 'skill' },
    { label: 'Recovery Techniques', type: 'skill' },
  ],
  fashion: [
    { label: 'Start a clothing line', type: 'goal' },
    { label: 'Build a fashion portfolio', type: 'goal' },
    { label: 'Learn pattern making', type: 'goal' },
    { label: 'Develop personal style', type: 'goal' },
    { label: 'Attend fashion week', type: 'goal' },
    { label: 'Fashion shows', type: 'interest' },
    { label: 'Style blogs', type: 'interest' },
    { label: 'Thrift shopping', type: 'interest' },
    { label: 'Fashion history', type: 'interest' },
    { label: 'Sustainable fashion', type: 'interest' },
    { label: 'Fashion Design', type: 'skill' },
    { label: 'Trend Analysis', type: 'skill' },
    { label: 'Sewing', type: 'skill' },
    { label: 'Styling', type: 'skill' },
    { label: 'Textile Knowledge', type: 'skill' },
  ],
  realestate: [
    { label: 'Buy first property', type: 'goal' },
    { label: 'Get real estate license', type: 'goal' },
    { label: 'Build investment portfolio', type: 'goal' },
    { label: 'Learn property valuation', type: 'goal' },
    { label: 'Network with agents', type: 'goal' },
    { label: 'Property tours', type: 'interest' },
    { label: 'Real estate podcasts', type: 'interest' },
    { label: 'Market trends', type: 'interest' },
    { label: 'Home renovation shows', type: 'interest' },
    { label: 'Neighborhood development', type: 'interest' },
    { label: 'Market Analysis', type: 'skill' },
    { label: 'Property Valuation', type: 'skill' },
    { label: 'Negotiation', type: 'skill' },
    { label: 'Contract Review', type: 'skill' },
    { label: 'Investment Analysis', type: 'skill' },
  ],
  food: [
    { label: 'Master 5 recipes', type: 'goal' },
    { label: 'Start a food blog', type: 'goal' },
    { label: 'Learn baking techniques', type: 'goal' },
    { label: 'Host a dinner party', type: 'goal' },
    { label: 'Explore international cuisine', type: 'goal' },
    { label: 'Cooking classes', type: 'interest' },
    { label: 'Food festivals', type: 'interest' },
    { label: 'Recipe blogs', type: 'interest' },
    { label: 'Farmers markets', type: 'interest' },
    { label: 'Wine tasting', type: 'interest' },
    { label: 'Knife Skills', type: 'skill' },
    { label: 'Recipe Development', type: 'skill' },
    { label: 'Flavor Pairing', type: 'skill' },
    { label: 'Food Presentation', type: 'skill' },
    { label: 'Menu Planning', type: 'skill' },
  ],
  productivity: [
    { label: 'Build a morning routine', type: 'goal' },
    { label: 'Master time management', type: 'goal' },
    { label: 'Implement GTD system', type: 'goal' },
    { label: 'Reduce digital distractions', type: 'goal' },
    { label: 'Achieve inbox zero', type: 'goal' },
    { label: 'Productivity apps', type: 'interest' },
    { label: 'Time management books', type: 'interest' },
    { label: 'Workflow optimization', type: 'interest' },
    { label: 'Minimalism', type: 'interest' },
    { label: 'Digital organization', type: 'interest' },
    { label: 'Task Management', type: 'skill' },
    { label: 'Goal Setting', type: 'skill' },
    { label: 'Priority Management', type: 'skill' },
    { label: 'Workflow Automation', type: 'skill' },
    { label: 'Focus Techniques', type: 'skill' },
  ],
  sports: [
    { label: 'Join a sports team', type: 'goal' },
    { label: 'Improve athletic performance', type: 'goal' },
    { label: 'Learn a new sport', type: 'goal' },
    { label: 'Compete in tournament', type: 'goal' },
    { label: 'Achieve personal best', type: 'goal' },
    { label: 'Sports events', type: 'interest' },
    { label: 'Team practices', type: 'interest' },
    { label: 'Sports analytics', type: 'interest' },
    { label: 'Athlete documentaries', type: 'interest' },
    { label: 'Sports nutrition', type: 'interest' },
    { label: 'Coaching', type: 'skill' },
    { label: 'Team Strategy', type: 'skill' },
    { label: 'Physical Conditioning', type: 'skill' },
    { label: 'Game Analysis', type: 'skill' },
    { label: 'Sports Psychology', type: 'skill' },
  ],
  science: [
    { label: 'Conduct research', type: 'goal' },
    { label: 'Publish a paper', type: 'goal' },
    { label: 'Learn lab techniques', type: 'goal' },
    { label: 'Attend science conference', type: 'goal' },
    { label: 'Master scientific method', type: 'goal' },
    { label: 'Science conferences', type: 'interest' },
    { label: 'Research journals', type: 'interest' },
    { label: 'Science podcasts', type: 'interest' },
    { label: 'Laboratory work', type: 'interest' },
    { label: 'Scientific debates', type: 'interest' },
    { label: 'Data Analysis', type: 'skill' },
    { label: 'Research Methodology', type: 'skill' },
    { label: 'Lab Techniques', type: 'skill' },
    { label: 'Scientific Writing', type: 'skill' },
    { label: 'Experimental Design', type: 'skill' },
  ],
};