"""Fix array columns

Revision ID: 1ff1372134eb
Revises: b10424676707
Create Date: 2025-07-09 09:04:55.810399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ff1372134eb'
down_revision: Union[str, Sequence[str], None] = 'b10424676707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorprofile',
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expertise', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('experience_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available_times', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('currently_open_to_mentees', sa.Boolean(), nullable=False),
    sa.Column('contact_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_mentorprofile_user_id'), 'mentorprofile', ['user_id'], unique=False)
    op.add_column('userprofile', sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('userprofile', sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_userprofile_user_id'), 'userprofile', ['user_id'], unique=False)
    op.create_index(op.f('ix_userrole_role_id'), 'userrole', ['role_id'], unique=False)
    op.create_index(op.f('ix_userrole_user_id'), 'userrole', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userrole_user_id'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_role_id'), table_name='userrole')
    op.drop_index(op.f('ix_userprofile_user_id'), table_name='userprofile')
    op.drop_column('userprofile', 'availability')
    op.drop_column('userprofile', 'interests')
    op.drop_index(op.f('ix_mentorprofile_user_id'), table_name='mentorprofile')
    op.drop_table('mentorprofile')
    # ### end Alembic commands ###
