"""add status to BoardList

Revision ID: 294e54b4d726
Revises: 0e0b09ea40d5
Create Date: 2025-08-14 20:04:48.843013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '294e54b4d726'
down_revision: Union[str, Sequence[str], None] = '0e0b09ea40d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardlist', sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='cardstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boardlist', 'status')
    # ### end Alembic commands ###
