"""Add uuid and banner_url to (MentorSession, MentorService) and (MentorService) respectively

Revision ID: 642df376bec1
Revises: d226515c66ba
Create Date: 2025-10-23 15:36:50.143554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '642df376bec1'
down_revision: Union[str, Sequence[str], None] = 'd226515c66ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorservice', sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('mentorservice', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_mentorservice_uuid'), 'mentorservice', ['uuid'], unique=True)
    op.add_column('mentorsession', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_mentorsession_uuid'), 'mentorsession', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorsession_uuid'), table_name='mentorsession')
    op.drop_column('mentorsession', 'uuid')
    op.drop_index(op.f('ix_mentorservice_uuid'), table_name='mentorservice')
    op.drop_column('mentorservice', 'uuid')
    op.drop_column('mentorservice', 'banner_url')
    # ### end Alembic commands ###
