"""Add cover_image col to the UserPublic

Revision ID: 677e478b5d93
Revises: f16274d17ca6
Create Date: 2025-07-29 13:32:12.265649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '677e478b5d93'
down_revision: Union[str, Sequence[str], None] = 'f16274d17ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_image')
    # ### end Alembic commands ###
