"""Fix Card.position col typo

Revision ID: 6a6aa41fcab9
Revises: 294e54b4d726
Create Date: 2025-08-19 03:19:32.589749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '6a6aa41fcab9'
down_revision: Union[str, Sequence[str], None] = '294e54b4d726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('is_llm_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_foreign_key(None, 'board', 'goal', ['goal_id'], ['id'])
    op.add_column('boardlist', sa.Column('is_llm_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('card', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('card', sa.Column('roadmap_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'roadmap', ['roadmap_id'], ['id'])
    op.drop_column('card', 'posistion')
    op.add_column('roadmap', sa.Column('is_llm_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap', 'is_llm_generated')
    op.add_column('card', sa.Column('posistion', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'roadmap_id')
    op.drop_column('card', 'position')
    op.drop_column('boardlist', 'is_llm_generated')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'is_llm_generated')
    op.drop_column('board', 'goal_id')
    # ### end Alembic commands ###
