"""Update  field to 

Revision ID: 6b2781cd14be
Revises: 642df376bec1
Create Date: 2025-10-24 10:16:05.216648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '6b2781cd14be'
down_revision: Union[str, Sequence[str], None] = '642df376bec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorservice', sa.Column('price_usd', sa.Float(), nullable=True))
    op.drop_column('mentorservice', 'price')
    op.add_column('mentorsession', sa.Column('price_usd', sa.Float(), nullable=True))
    op.drop_column('mentorsession', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorsession', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('mentorsession', 'price_usd')
    op.add_column('mentorservice', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('mentorservice', 'price_usd')
    # ### end Alembic commands ###
