"""Add allow_public_availability_view to MentorSettings Table

Revision ID: 8178065e7069
Revises: 0bf791ab1a03
Create Date: 2025-11-26 02:56:36.929060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '8178065e7069'
down_revision: Union[str, Sequence[str], None] = '0bf791ab1a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorsettings', sa.Column('allow_public_availability_view', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorsettings', 'allow_public_availability_view')
    # ### end Alembic commands ###
