"""Remove availability, add area_of_focus to user profile

Revision ID: 81b7954509b5
Revises: c18a7f8fbea3
Create Date: 2025-07-13 20:16:11.599578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81b7954509b5'
down_revision: Union[str, Sequence[str], None] = 'c18a7f8fbea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('area_of_focus', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('userprofile', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('availability', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('userprofile', 'area_of_focus')
    # ### end Alembic commands ###
