"""set auto_default_booking to True

Revision ID: 84618660f2c3
Revises: b0a39b4ca65d
Create Date: 2026-02-05 18:58:23.965663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "84618660f2c3"
down_revision: Union[str, Sequence[str], None] = "b0a39b4ca65d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mentorsettings",
        "auto_accept_bookings",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        nullable=False,
    )
    # ### end Alembic commands ###
    
    op.execute(
        """
        UPDATE mentorsettings
        SET auto_accept_bookings = true
        WHERE auto_accept_bookings IS NULL
           OR auto_accept_bookings = false
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mentorsettings",
        "auto_accept_bookings",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        nullable=True,
    )
    # ### end Alembic commands ###
