"""Add cols-data to MentorPubic class

Revision ID: 8eaf66e7875c
Revises: 6a6aa41fcab9
Create Date: 2025-10-19 14:24:42.228098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eaf66e7875c'
down_revision: Union[str, Sequence[str], None] = '6a6aa41fcab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorprofile', sa.Column('mentor_type', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mentorprofile', sa.Column('areas_of_expertise', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mentorprofile', sa.Column('session_types', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mentorprofile', sa.Column('session_durations', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('mentorprofile', sa.Column('pricing', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('mentorprofile', sa.Column('max_mentees', sa.Integer(), nullable=True))
    op.add_column('mentorprofile', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mentorprofile', sa.Column('weekly_schedule', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('mentorprofile', sa.Column('booking_buffer_hours', sa.Integer(), nullable=True))
    op.add_column('mentorprofile', sa.Column('session_gap_minutes', sa.Integer(), nullable=True))
    op.add_column('mentorprofile', sa.Column('mentorship_philosophy', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('mentorprofile', sa.Column('ideal_mentee_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.add_column('mentorprofile', sa.Column('communication_style', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mentorprofile', sa.Column('response_time_hours', sa.Integer(), nullable=True))
    op.add_column('mentorprofile', sa.Column('profile_visibility', sa.Boolean(), nullable=False))
    op.add_column('mentorprofile', sa.Column('auto_accept_bookings', sa.Boolean(), nullable=False))
    op.add_column('mentorprofile', sa.Column('require_intro_message', sa.Boolean(), nullable=False))
    op.add_column('mentorprofile', sa.Column('total_sessions', sa.Integer(), nullable=False))
    op.add_column('mentorprofile', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('mentorprofile', sa.Column('total_mentees', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorprofile', 'total_mentees')
    op.drop_column('mentorprofile', 'average_rating')
    op.drop_column('mentorprofile', 'total_sessions')
    op.drop_column('mentorprofile', 'require_intro_message')
    op.drop_column('mentorprofile', 'auto_accept_bookings')
    op.drop_column('mentorprofile', 'profile_visibility')
    op.drop_column('mentorprofile', 'response_time_hours')
    op.drop_column('mentorprofile', 'communication_style')
    op.drop_column('mentorprofile', 'ideal_mentee_description')
    op.drop_column('mentorprofile', 'mentorship_philosophy')
    op.drop_column('mentorprofile', 'session_gap_minutes')
    op.drop_column('mentorprofile', 'booking_buffer_hours')
    op.drop_column('mentorprofile', 'weekly_schedule')
    op.drop_column('mentorprofile', 'timezone')
    op.drop_column('mentorprofile', 'max_mentees')
    op.drop_column('mentorprofile', 'pricing')
    op.drop_column('mentorprofile', 'session_durations')
    op.drop_column('mentorprofile', 'session_types')
    op.drop_column('mentorprofile', 'areas_of_expertise')
    op.drop_column('mentorprofile', 'mentor_type')
    # ### end Alembic commands ###
