"""Add cover_image to MentorSessionBase

Revision ID: 95c705c77fa1
Revises: 37ac9939d960
Create Date: 2025-10-27 15:46:11.508077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c705c77fa1'
down_revision: Union[str, Sequence[str], None] = '37ac9939d960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorsession', sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mentorsession', sa.Column('preparation_materials', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorsession', 'preparation_materials')
    op.drop_column('mentorsession', 'cover_image')
    # ### end Alembic commands ###
