"""Add tables to handle Session bookings

Revision ID: a32cfcb47494
Revises: 6b2781cd14be
Create Date: 2025-10-26 20:44:12.003079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'a32cfcb47494'
down_revision: Union[str, Sequence[str], None] = '6b2781cd14be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorsessionbooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['mentorsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorsessionbooking_mentee_id'), 'mentorsessionbooking', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentorsessionbooking_session_id'), 'mentorsessionbooking', ['session_id'], unique=False)
    op.create_index(op.f('ix_mentorsessionbooking_uuid'), 'mentorsessionbooking', ['uuid'], unique=True)
    op.add_column('mentorsession', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('mentorsession', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('mentorsession', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('mentorsession', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.add_column('mentorsession', sa.Column('max_bookings', sa.Integer(), nullable=True))
    op.add_column('mentorsession', sa.Column('location_type', sa.String(), nullable=False))
    op.add_column('mentorsession', sa.Column('meeting_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mentorsession', sa.Column('physical_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('mentorsession', 'max_bookings_per_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorsession', sa.Column('max_bookings_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('mentorsession', 'physical_address')
    op.drop_column('mentorsession', 'meeting_link')
    op.drop_column('mentorsession', 'location_type')
    op.drop_column('mentorsession', 'max_bookings')
    op.drop_column('mentorsession', 'is_cancelled')
    op.drop_column('mentorsession', 'timezone')
    op.drop_column('mentorsession', 'end_time')
    op.drop_column('mentorsession', 'start_time')
    op.drop_index(op.f('ix_mentorsessionbooking_uuid'), table_name='mentorsessionbooking')
    op.drop_index(op.f('ix_mentorsessionbooking_session_id'), table_name='mentorsessionbooking')
    op.drop_index(op.f('ix_mentorsessionbooking_mentee_id'), table_name='mentorsessionbooking')
    op.drop_table('mentorsessionbooking')
    # ### end Alembic commands ###
