"""remove session_type

Revision ID: aa1884f22417
Revises: 84618660f2c3
Create Date: 2026-02-23 14:57:58.108359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'aa1884f22417'
down_revision: Union[str, Sequence[str], None] = '84618660f2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorsession', 'session_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorsession', sa.Column('session_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
