"""rename title to professional_title and add about field

Revision ID: bfb414d9da1c
Revises: 8eaf66e7875c
Create Date: 2025-10-20 10:01:54.779389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'bfb414d9da1c'
down_revision: Union[str, Sequence[str], None] = '8eaf66e7875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userprofile', sa.Column('about', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('userprofile', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('userprofile', 'about')
    op.drop_column('userprofile', 'title')
    # ### end Alembic commands ###
