"""Remove title from MentorProfile

Revision ID: d226515c66ba
Revises: bfb414d9da1c
Create Date: 2025-10-22 09:19:16.626955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd226515c66ba'
down_revision: Union[str, Sequence[str], None] = 'bfb414d9da1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorservice',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('highlights', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentorprofile.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentorsession',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_type', sa.Enum('ONE_ON_ONE', 'CODE_REVIEW', name='sessiontype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_bookings_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentorprofile.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentorsettings',
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('currently_open_to_mentees', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.Boolean(), nullable=False),
    sa.Column('auto_accept_bookings', sa.Boolean(), nullable=False),
    sa.Column('require_intro_message', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available_times', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weekly_schedule', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('booking_buffer_hours', sa.Integer(), nullable=False),
    sa.Column('session_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('max_mentees', sa.Integer(), nullable=True),
    sa.Column('mentorship_philosophy', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('ideal_mentee_description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('communication_style', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentorprofile.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mentorprofile', sa.Column('industries', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('mentorprofile', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mentorprofile', 'expertise',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('mentorprofile', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mentorprofile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('mentorprofile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('mentorprofile', 'response_time_hours')
    op.drop_column('mentorprofile', 'currently_open_to_mentees')
    op.drop_column('mentorprofile', 'weekly_schedule')
    op.drop_column('mentorprofile', 'auto_accept_bookings')
    op.drop_column('mentorprofile', 'profile_visibility')
    op.drop_column('mentorprofile', 'available_times')
    op.drop_column('mentorprofile', 'require_intro_message')
    op.drop_column('mentorprofile', 'communication_style')
    op.drop_column('mentorprofile', 'areas_of_expertise')
    op.drop_column('mentorprofile', 'session_types')
    op.drop_column('mentorprofile', 'booking_buffer_hours')
    op.drop_column('mentorprofile', 'session_gap_minutes')
    op.drop_column('mentorprofile', 'session_durations')
    op.drop_column('mentorprofile', 'timezone')
    op.drop_column('mentorprofile', 'mentorship_philosophy')
    op.drop_column('mentorprofile', 'max_mentees')
    op.drop_column('mentorprofile', 'ideal_mentee_description')
    op.drop_column('mentorprofile', 'industry')
    op.drop_column('mentorprofile', 'pricing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorprofile', sa.Column('pricing', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('ideal_mentee_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('max_mentees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('mentorship_philosophy', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('session_durations', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('session_gap_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('booking_buffer_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('session_types', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('areas_of_expertise', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('communication_style', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('require_intro_message', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mentorprofile', sa.Column('available_times', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('profile_visibility', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mentorprofile', sa.Column('auto_accept_bookings', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mentorprofile', sa.Column('weekly_schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mentorprofile', sa.Column('currently_open_to_mentees', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('mentorprofile', sa.Column('response_time_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('mentorprofile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mentorprofile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mentorprofile', 'experience_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mentorprofile', 'expertise',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('mentorprofile', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mentorprofile', 'industries')
    op.drop_table('mentorsettings')
    op.drop_table('mentorsession')
    op.drop_table('mentorservice')
    # ### end Alembic commands ###
