"""Remove updated_created_at -> MentorSettings

Revision ID: ea700f0c7cda
Revises: e12883f0870a
Create Date: 2025-11-07 05:57:58.086038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea700f0c7cda'
down_revision: Union[str, Sequence[str], None] = 'e12883f0870a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentorsession', 'session_type',
               existing_type=postgresql.ENUM('ONE_ON_ONE', 'CODE_REVIEW', name='sessiontype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentorsession', 'session_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ONE_ON_ONE', 'CODE_REVIEW', name='sessiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###
