"""Add contact_details to userprofile

Revision ID: f16274d17ca6
Revises: 81b7954509b5
Create Date: 2025-07-29 12:35:47.577978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16274d17ca6'
down_revision: Union[str, Sequence[str], None] = '81b7954509b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorprofile', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mentorprofile', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mentorprofile', sa.Column('badges', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('mentorprofile', 'contact_details')
    op.add_column('userprofile', sa.Column('contact_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'contact_details')
    op.add_column('mentorprofile', sa.Column('contact_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('mentorprofile', 'badges')
    op.drop_column('mentorprofile', 'tags')
    op.drop_column('mentorprofile', 'title')
    # ### end Alembic commands ###
