/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as CrackmodeIndexRouteImport } from './routes/crackmode/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as CrackmodeDocsRouteImport } from './routes/crackmode/docs'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutProfileSetupRouteImport } from './routes/_layout/profile-setup'
import { Route as LayoutExploreRouteImport } from './routes/_layout/explore'
import { Route as CrackmodeDocsIndexRouteImport } from './routes/crackmode/docs/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutDashboardProfileRouteImport } from './routes/_layout/dashboard/profile'
import { Route as CrackmodeDocsLeetcode75IndexRouteImport } from './routes/crackmode/docs/leetcode75/index'
import { Route as CrackmodeDocsIntroductionIndexRouteImport } from './routes/crackmode/docs/introduction/index'
import { Route as CrackmodeDocsProblemsUniqueNumberOfOccurrencesRouteImport } from './routes/crackmode/docs/problems/unique-number-of-occurrences'
import { Route as CrackmodeDocsProblemsNumberOfGoodPairsRouteImport } from './routes/crackmode/docs/problems/number-of-good-pairs'
import { Route as CrackmodeDocsProblemsMostCommonWordRouteImport } from './routes/crackmode/docs/problems/most-common-word'
import { Route as CrackmodeDocsProblemsMissingNumberRouteImport } from './routes/crackmode/docs/problems/missing-number'
import { Route as CrackmodeDocsProblemsLongestPalindromeRouteImport } from './routes/crackmode/docs/problems/longest-palindrome'
import { Route as CrackmodeDocsProblemsLongestConsecutiveSequenceRouteImport } from './routes/crackmode/docs/problems/longest-consecutive-sequence'
import { Route as CrackmodeDocsProblemsImplementStackUsingQueuesRouteImport } from './routes/crackmode/docs/problems/implement-stack-using-queues'
import { Route as CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRouteImport } from './routes/crackmode/docs/problems/find-the-difference-of-two-arrays'
import { Route as CrackmodeDocsProblemsFindTheDifferenceRouteImport } from './routes/crackmode/docs/problems/find-the-difference'
import { Route as CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport } from './routes/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
import { Route as CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRouteImport } from './routes/crackmode/docs/problems/find-all-duplicates-in-an-array'
import { Route as CrackmodeDocsProblemsDistributeCandiesRouteImport } from './routes/crackmode/docs/problems/distribute-candies'
import { Route as CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport } from './routes/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
import { Route as CrackmodeDocsLeetcode75ArraysStringsIndexRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/index'
import { Route as CrackmodeDocsLeetcode75ArraysStringsStringCompressionRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/string-compression'
import { Route as CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
import { Route as CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
import { Route as CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
import { Route as CrackmodeDocsLeetcode75ArraysStringsIntroductionRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/introduction'
import { Route as CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
import { Route as CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRouteImport } from './routes/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CrackmodeIndexRoute = CrackmodeIndexRouteImport.update({
  id: '/crackmode/',
  path: '/crackmode/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const CrackmodeDocsRoute = CrackmodeDocsRouteImport.update({
  id: '/crackmode/docs',
  path: '/crackmode/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProfileSetupRoute = LayoutProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const CrackmodeDocsIndexRoute = CrackmodeDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrackmodeDocsRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardProfileRoute = LayoutDashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const CrackmodeDocsLeetcode75IndexRoute =
  CrackmodeDocsLeetcode75IndexRouteImport.update({
    id: '/leetcode75/',
    path: '/leetcode75/',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsIntroductionIndexRoute =
  CrackmodeDocsIntroductionIndexRouteImport.update({
    id: '/introduction/',
    path: '/introduction/',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute =
  CrackmodeDocsProblemsUniqueNumberOfOccurrencesRouteImport.update({
    id: '/problems/unique-number-of-occurrences',
    path: '/problems/unique-number-of-occurrences',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsNumberOfGoodPairsRoute =
  CrackmodeDocsProblemsNumberOfGoodPairsRouteImport.update({
    id: '/problems/number-of-good-pairs',
    path: '/problems/number-of-good-pairs',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsMostCommonWordRoute =
  CrackmodeDocsProblemsMostCommonWordRouteImport.update({
    id: '/problems/most-common-word',
    path: '/problems/most-common-word',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsMissingNumberRoute =
  CrackmodeDocsProblemsMissingNumberRouteImport.update({
    id: '/problems/missing-number',
    path: '/problems/missing-number',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsLongestPalindromeRoute =
  CrackmodeDocsProblemsLongestPalindromeRouteImport.update({
    id: '/problems/longest-palindrome',
    path: '/problems/longest-palindrome',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsLongestConsecutiveSequenceRoute =
  CrackmodeDocsProblemsLongestConsecutiveSequenceRouteImport.update({
    id: '/problems/longest-consecutive-sequence',
    path: '/problems/longest-consecutive-sequence',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsImplementStackUsingQueuesRoute =
  CrackmodeDocsProblemsImplementStackUsingQueuesRouteImport.update({
    id: '/problems/implement-stack-using-queues',
    path: '/problems/implement-stack-using-queues',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute =
  CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRouteImport.update({
    id: '/problems/find-the-difference-of-two-arrays',
    path: '/problems/find-the-difference-of-two-arrays',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsFindTheDifferenceRoute =
  CrackmodeDocsProblemsFindTheDifferenceRouteImport.update({
    id: '/problems/find-the-difference',
    path: '/problems/find-the-difference',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute =
  CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport.update({
    id: '/problems/find-all-numbers-disappeared-in-an-array',
    path: '/problems/find-all-numbers-disappeared-in-an-array',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute =
  CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRouteImport.update({
    id: '/problems/find-all-duplicates-in-an-array',
    path: '/problems/find-all-duplicates-in-an-array',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsDistributeCandiesRoute =
  CrackmodeDocsProblemsDistributeCandiesRouteImport.update({
    id: '/problems/distribute-candies',
    path: '/problems/distribute-candies',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute =
  CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport.update(
    {
      id: '/problems/check-if-number-has-equal-digit-count-and-digit-value',
      path: '/problems/check-if-number-has-equal-digit-count-and-digit-value',
      getParentRoute: () => CrackmodeDocsRoute,
    } as any,
  )
const CrackmodeDocsLeetcode75ArraysStringsIndexRoute =
  CrackmodeDocsLeetcode75ArraysStringsIndexRouteImport.update({
    id: '/leetcode75/arrays-strings/',
    path: '/leetcode75/arrays-strings/',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute =
  CrackmodeDocsLeetcode75ArraysStringsStringCompressionRouteImport.update({
    id: '/leetcode75/arrays-strings/string-compression',
    path: '/leetcode75/arrays-strings/string-compression',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute =
  CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport.update(
    {
      id: '/leetcode75/arrays-strings/product-of-array-except-self',
      path: '/leetcode75/arrays-strings/product-of-array-except-self',
      getParentRoute: () => CrackmodeDocsRoute,
    } as any,
  )
const CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute =
  CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport.update(
    {
      id: '/leetcode75/arrays-strings/merge-strings-alternately',
      path: '/leetcode75/arrays-strings/merge-strings-alternately',
      getParentRoute: () => CrackmodeDocsRoute,
    } as any,
  )
const CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute =
  CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport.update(
    {
      id: '/leetcode75/arrays-strings/kids-with-greatest-candies',
      path: '/leetcode75/arrays-strings/kids-with-greatest-candies',
      getParentRoute: () => CrackmodeDocsRoute,
    } as any,
  )
const CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute =
  CrackmodeDocsLeetcode75ArraysStringsIntroductionRouteImport.update({
    id: '/leetcode75/arrays-strings/introduction',
    path: '/leetcode75/arrays-strings/introduction',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)
const CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute =
  CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport.update(
    {
      id: '/leetcode75/arrays-strings/increasing-triplet-subsequence',
      path: '/leetcode75/arrays-strings/increasing-triplet-subsequence',
      getParentRoute: () => CrackmodeDocsRoute,
    } as any,
  )
const CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute =
  CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRouteImport.update({
    id: '/leetcode75/arrays-strings/gcd-of-strings',
    path: '/leetcode75/arrays-strings/gcd-of-strings',
    getParentRoute: () => CrackmodeDocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/explore': typeof LayoutExploreRoute
  '/profile-setup': typeof LayoutProfileSetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crackmode/docs': typeof CrackmodeDocsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/crackmode': typeof CrackmodeIndexRoute
  '/dashboard/profile': typeof LayoutDashboardProfileRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/crackmode/docs/': typeof CrackmodeDocsIndexRoute
  '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/crackmode/docs/problems/distribute-candies': typeof CrackmodeDocsProblemsDistributeCandiesRoute
  '/crackmode/docs/problems/find-all-duplicates-in-an-array': typeof CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array': typeof CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/crackmode/docs/problems/find-the-difference': typeof CrackmodeDocsProblemsFindTheDifferenceRoute
  '/crackmode/docs/problems/find-the-difference-of-two-arrays': typeof CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/crackmode/docs/problems/implement-stack-using-queues': typeof CrackmodeDocsProblemsImplementStackUsingQueuesRoute
  '/crackmode/docs/problems/longest-consecutive-sequence': typeof CrackmodeDocsProblemsLongestConsecutiveSequenceRoute
  '/crackmode/docs/problems/longest-palindrome': typeof CrackmodeDocsProblemsLongestPalindromeRoute
  '/crackmode/docs/problems/missing-number': typeof CrackmodeDocsProblemsMissingNumberRoute
  '/crackmode/docs/problems/most-common-word': typeof CrackmodeDocsProblemsMostCommonWordRoute
  '/crackmode/docs/problems/number-of-good-pairs': typeof CrackmodeDocsProblemsNumberOfGoodPairsRoute
  '/crackmode/docs/problems/unique-number-of-occurrences': typeof CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute
  '/crackmode/docs/introduction': typeof CrackmodeDocsIntroductionIndexRoute
  '/crackmode/docs/leetcode75': typeof CrackmodeDocsLeetcode75IndexRoute
  '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings': typeof CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/crackmode/docs/leetcode75/arrays-strings/introduction': typeof CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute
  '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/crackmode/docs/leetcode75/arrays-strings/string-compression': typeof CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute
  '/crackmode/docs/leetcode75/arrays-strings': typeof CrackmodeDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/explore': typeof LayoutExploreRoute
  '/profile-setup': typeof LayoutProfileSetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/crackmode': typeof CrackmodeIndexRoute
  '/dashboard/profile': typeof LayoutDashboardProfileRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/crackmode/docs': typeof CrackmodeDocsIndexRoute
  '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/crackmode/docs/problems/distribute-candies': typeof CrackmodeDocsProblemsDistributeCandiesRoute
  '/crackmode/docs/problems/find-all-duplicates-in-an-array': typeof CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array': typeof CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/crackmode/docs/problems/find-the-difference': typeof CrackmodeDocsProblemsFindTheDifferenceRoute
  '/crackmode/docs/problems/find-the-difference-of-two-arrays': typeof CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/crackmode/docs/problems/implement-stack-using-queues': typeof CrackmodeDocsProblemsImplementStackUsingQueuesRoute
  '/crackmode/docs/problems/longest-consecutive-sequence': typeof CrackmodeDocsProblemsLongestConsecutiveSequenceRoute
  '/crackmode/docs/problems/longest-palindrome': typeof CrackmodeDocsProblemsLongestPalindromeRoute
  '/crackmode/docs/problems/missing-number': typeof CrackmodeDocsProblemsMissingNumberRoute
  '/crackmode/docs/problems/most-common-word': typeof CrackmodeDocsProblemsMostCommonWordRoute
  '/crackmode/docs/problems/number-of-good-pairs': typeof CrackmodeDocsProblemsNumberOfGoodPairsRoute
  '/crackmode/docs/problems/unique-number-of-occurrences': typeof CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute
  '/crackmode/docs/introduction': typeof CrackmodeDocsIntroductionIndexRoute
  '/crackmode/docs/leetcode75': typeof CrackmodeDocsLeetcode75IndexRoute
  '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings': typeof CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/crackmode/docs/leetcode75/arrays-strings/introduction': typeof CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute
  '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/crackmode/docs/leetcode75/arrays-strings/string-compression': typeof CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute
  '/crackmode/docs/leetcode75/arrays-strings': typeof CrackmodeDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/profile-setup': typeof LayoutProfileSetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/crackmode/docs': typeof CrackmodeDocsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/crackmode/': typeof CrackmodeIndexRoute
  '/_layout/dashboard/profile': typeof LayoutDashboardProfileRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/crackmode/docs/': typeof CrackmodeDocsIndexRoute
  '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': typeof CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  '/crackmode/docs/problems/distribute-candies': typeof CrackmodeDocsProblemsDistributeCandiesRoute
  '/crackmode/docs/problems/find-all-duplicates-in-an-array': typeof CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute
  '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array': typeof CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  '/crackmode/docs/problems/find-the-difference': typeof CrackmodeDocsProblemsFindTheDifferenceRoute
  '/crackmode/docs/problems/find-the-difference-of-two-arrays': typeof CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute
  '/crackmode/docs/problems/implement-stack-using-queues': typeof CrackmodeDocsProblemsImplementStackUsingQueuesRoute
  '/crackmode/docs/problems/longest-consecutive-sequence': typeof CrackmodeDocsProblemsLongestConsecutiveSequenceRoute
  '/crackmode/docs/problems/longest-palindrome': typeof CrackmodeDocsProblemsLongestPalindromeRoute
  '/crackmode/docs/problems/missing-number': typeof CrackmodeDocsProblemsMissingNumberRoute
  '/crackmode/docs/problems/most-common-word': typeof CrackmodeDocsProblemsMostCommonWordRoute
  '/crackmode/docs/problems/number-of-good-pairs': typeof CrackmodeDocsProblemsNumberOfGoodPairsRoute
  '/crackmode/docs/problems/unique-number-of-occurrences': typeof CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute
  '/crackmode/docs/introduction/': typeof CrackmodeDocsIntroductionIndexRoute
  '/crackmode/docs/leetcode75/': typeof CrackmodeDocsLeetcode75IndexRoute
  '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings': typeof CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute
  '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': typeof CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  '/crackmode/docs/leetcode75/arrays-strings/introduction': typeof CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute
  '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies': typeof CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately': typeof CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self': typeof CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  '/crackmode/docs/leetcode75/arrays-strings/string-compression': typeof CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute
  '/crackmode/docs/leetcode75/arrays-strings/': typeof CrackmodeDocsLeetcode75ArraysStringsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/explore'
    | '/profile-setup'
    | '/auth/callback'
    | '/crackmode/docs'
    | '/'
    | '/crackmode'
    | '/dashboard/profile'
    | '/dashboard'
    | '/crackmode/docs/'
    | '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/crackmode/docs/problems/distribute-candies'
    | '/crackmode/docs/problems/find-all-duplicates-in-an-array'
    | '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/crackmode/docs/problems/find-the-difference'
    | '/crackmode/docs/problems/find-the-difference-of-two-arrays'
    | '/crackmode/docs/problems/implement-stack-using-queues'
    | '/crackmode/docs/problems/longest-consecutive-sequence'
    | '/crackmode/docs/problems/longest-palindrome'
    | '/crackmode/docs/problems/missing-number'
    | '/crackmode/docs/problems/most-common-word'
    | '/crackmode/docs/problems/number-of-good-pairs'
    | '/crackmode/docs/problems/unique-number-of-occurrences'
    | '/crackmode/docs/introduction'
    | '/crackmode/docs/leetcode75'
    | '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/crackmode/docs/leetcode75/arrays-strings/introduction'
    | '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/crackmode/docs/leetcode75/arrays-strings/string-compression'
    | '/crackmode/docs/leetcode75/arrays-strings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/explore'
    | '/profile-setup'
    | '/auth/callback'
    | '/'
    | '/crackmode'
    | '/dashboard/profile'
    | '/dashboard'
    | '/crackmode/docs'
    | '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/crackmode/docs/problems/distribute-candies'
    | '/crackmode/docs/problems/find-all-duplicates-in-an-array'
    | '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/crackmode/docs/problems/find-the-difference'
    | '/crackmode/docs/problems/find-the-difference-of-two-arrays'
    | '/crackmode/docs/problems/implement-stack-using-queues'
    | '/crackmode/docs/problems/longest-consecutive-sequence'
    | '/crackmode/docs/problems/longest-palindrome'
    | '/crackmode/docs/problems/missing-number'
    | '/crackmode/docs/problems/most-common-word'
    | '/crackmode/docs/problems/number-of-good-pairs'
    | '/crackmode/docs/problems/unique-number-of-occurrences'
    | '/crackmode/docs/introduction'
    | '/crackmode/docs/leetcode75'
    | '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/crackmode/docs/leetcode75/arrays-strings/introduction'
    | '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/crackmode/docs/leetcode75/arrays-strings/string-compression'
    | '/crackmode/docs/leetcode75/arrays-strings'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/_layout/explore'
    | '/_layout/profile-setup'
    | '/auth/callback'
    | '/crackmode/docs'
    | '/_layout/'
    | '/crackmode/'
    | '/_layout/dashboard/profile'
    | '/_layout/dashboard/'
    | '/crackmode/docs/'
    | '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
    | '/crackmode/docs/problems/distribute-candies'
    | '/crackmode/docs/problems/find-all-duplicates-in-an-array'
    | '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
    | '/crackmode/docs/problems/find-the-difference'
    | '/crackmode/docs/problems/find-the-difference-of-two-arrays'
    | '/crackmode/docs/problems/implement-stack-using-queues'
    | '/crackmode/docs/problems/longest-consecutive-sequence'
    | '/crackmode/docs/problems/longest-palindrome'
    | '/crackmode/docs/problems/missing-number'
    | '/crackmode/docs/problems/most-common-word'
    | '/crackmode/docs/problems/number-of-good-pairs'
    | '/crackmode/docs/problems/unique-number-of-occurrences'
    | '/crackmode/docs/introduction/'
    | '/crackmode/docs/leetcode75/'
    | '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'
    | '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
    | '/crackmode/docs/leetcode75/arrays-strings/introduction'
    | '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
    | '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
    | '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
    | '/crackmode/docs/leetcode75/arrays-strings/string-compression'
    | '/crackmode/docs/leetcode75/arrays-strings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CrackmodeDocsRoute: typeof CrackmodeDocsRouteWithChildren
  CrackmodeIndexRoute: typeof CrackmodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crackmode/': {
      id: '/crackmode/'
      path: '/crackmode'
      fullPath: '/crackmode'
      preLoaderRoute: typeof CrackmodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/crackmode/docs': {
      id: '/crackmode/docs'
      path: '/crackmode/docs'
      fullPath: '/crackmode/docs'
      preLoaderRoute: typeof CrackmodeDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/profile-setup': {
      id: '/_layout/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutProfileSetupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/crackmode/docs/': {
      id: '/crackmode/docs/'
      path: '/'
      fullPath: '/crackmode/docs/'
      preLoaderRoute: typeof CrackmodeDocsIndexRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/profile': {
      id: '/_layout/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof LayoutDashboardProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/crackmode/docs/leetcode75/': {
      id: '/crackmode/docs/leetcode75/'
      path: '/leetcode75'
      fullPath: '/crackmode/docs/leetcode75'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75IndexRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/introduction/': {
      id: '/crackmode/docs/introduction/'
      path: '/introduction'
      fullPath: '/crackmode/docs/introduction'
      preLoaderRoute: typeof CrackmodeDocsIntroductionIndexRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/unique-number-of-occurrences': {
      id: '/crackmode/docs/problems/unique-number-of-occurrences'
      path: '/problems/unique-number-of-occurrences'
      fullPath: '/crackmode/docs/problems/unique-number-of-occurrences'
      preLoaderRoute: typeof CrackmodeDocsProblemsUniqueNumberOfOccurrencesRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/number-of-good-pairs': {
      id: '/crackmode/docs/problems/number-of-good-pairs'
      path: '/problems/number-of-good-pairs'
      fullPath: '/crackmode/docs/problems/number-of-good-pairs'
      preLoaderRoute: typeof CrackmodeDocsProblemsNumberOfGoodPairsRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/most-common-word': {
      id: '/crackmode/docs/problems/most-common-word'
      path: '/problems/most-common-word'
      fullPath: '/crackmode/docs/problems/most-common-word'
      preLoaderRoute: typeof CrackmodeDocsProblemsMostCommonWordRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/missing-number': {
      id: '/crackmode/docs/problems/missing-number'
      path: '/problems/missing-number'
      fullPath: '/crackmode/docs/problems/missing-number'
      preLoaderRoute: typeof CrackmodeDocsProblemsMissingNumberRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/longest-palindrome': {
      id: '/crackmode/docs/problems/longest-palindrome'
      path: '/problems/longest-palindrome'
      fullPath: '/crackmode/docs/problems/longest-palindrome'
      preLoaderRoute: typeof CrackmodeDocsProblemsLongestPalindromeRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/longest-consecutive-sequence': {
      id: '/crackmode/docs/problems/longest-consecutive-sequence'
      path: '/problems/longest-consecutive-sequence'
      fullPath: '/crackmode/docs/problems/longest-consecutive-sequence'
      preLoaderRoute: typeof CrackmodeDocsProblemsLongestConsecutiveSequenceRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/implement-stack-using-queues': {
      id: '/crackmode/docs/problems/implement-stack-using-queues'
      path: '/problems/implement-stack-using-queues'
      fullPath: '/crackmode/docs/problems/implement-stack-using-queues'
      preLoaderRoute: typeof CrackmodeDocsProblemsImplementStackUsingQueuesRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/find-the-difference-of-two-arrays': {
      id: '/crackmode/docs/problems/find-the-difference-of-two-arrays'
      path: '/problems/find-the-difference-of-two-arrays'
      fullPath: '/crackmode/docs/problems/find-the-difference-of-two-arrays'
      preLoaderRoute: typeof CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/find-the-difference': {
      id: '/crackmode/docs/problems/find-the-difference'
      path: '/problems/find-the-difference'
      fullPath: '/crackmode/docs/problems/find-the-difference'
      preLoaderRoute: typeof CrackmodeDocsProblemsFindTheDifferenceRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array': {
      id: '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
      path: '/problems/find-all-numbers-disappeared-in-an-array'
      fullPath: '/crackmode/docs/problems/find-all-numbers-disappeared-in-an-array'
      preLoaderRoute: typeof CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/find-all-duplicates-in-an-array': {
      id: '/crackmode/docs/problems/find-all-duplicates-in-an-array'
      path: '/problems/find-all-duplicates-in-an-array'
      fullPath: '/crackmode/docs/problems/find-all-duplicates-in-an-array'
      preLoaderRoute: typeof CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/distribute-candies': {
      id: '/crackmode/docs/problems/distribute-candies'
      path: '/problems/distribute-candies'
      fullPath: '/crackmode/docs/problems/distribute-candies'
      preLoaderRoute: typeof CrackmodeDocsProblemsDistributeCandiesRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value': {
      id: '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
      path: '/problems/check-if-number-has-equal-digit-count-and-digit-value'
      fullPath: '/crackmode/docs/problems/check-if-number-has-equal-digit-count-and-digit-value'
      preLoaderRoute: typeof CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/': {
      id: '/crackmode/docs/leetcode75/arrays-strings/'
      path: '/leetcode75/arrays-strings'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIndexRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/string-compression': {
      id: '/crackmode/docs/leetcode75/arrays-strings/string-compression'
      path: '/leetcode75/arrays-strings/string-compression'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/string-compression'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsStringCompressionRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self': {
      id: '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
      path: '/leetcode75/arrays-strings/product-of-array-except-self'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/product-of-array-except-self'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately': {
      id: '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
      path: '/leetcode75/arrays-strings/merge-strings-alternately'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/merge-strings-alternately'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies': {
      id: '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
      path: '/leetcode75/arrays-strings/kids-with-greatest-candies'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/kids-with-greatest-candies'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/introduction': {
      id: '/crackmode/docs/leetcode75/arrays-strings/introduction'
      path: '/leetcode75/arrays-strings/introduction'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/introduction'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIntroductionRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence': {
      id: '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
      path: '/leetcode75/arrays-strings/increasing-triplet-subsequence'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/increasing-triplet-subsequence'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
    '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings': {
      id: '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'
      path: '/leetcode75/arrays-strings/gcd-of-strings'
      fullPath: '/crackmode/docs/leetcode75/arrays-strings/gcd-of-strings'
      preLoaderRoute: typeof CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRouteImport
      parentRoute: typeof CrackmodeDocsRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutProfileSetupRoute: typeof LayoutProfileSetupRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashboardProfileRoute: typeof LayoutDashboardProfileRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutProfileSetupRoute: LayoutProfileSetupRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashboardProfileRoute: LayoutDashboardProfileRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface CrackmodeDocsRouteChildren {
  CrackmodeDocsIndexRoute: typeof CrackmodeDocsIndexRoute
  CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute: typeof CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute
  CrackmodeDocsProblemsDistributeCandiesRoute: typeof CrackmodeDocsProblemsDistributeCandiesRoute
  CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute: typeof CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute
  CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute: typeof CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute
  CrackmodeDocsProblemsFindTheDifferenceRoute: typeof CrackmodeDocsProblemsFindTheDifferenceRoute
  CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute: typeof CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute
  CrackmodeDocsProblemsImplementStackUsingQueuesRoute: typeof CrackmodeDocsProblemsImplementStackUsingQueuesRoute
  CrackmodeDocsProblemsLongestConsecutiveSequenceRoute: typeof CrackmodeDocsProblemsLongestConsecutiveSequenceRoute
  CrackmodeDocsProblemsLongestPalindromeRoute: typeof CrackmodeDocsProblemsLongestPalindromeRoute
  CrackmodeDocsProblemsMissingNumberRoute: typeof CrackmodeDocsProblemsMissingNumberRoute
  CrackmodeDocsProblemsMostCommonWordRoute: typeof CrackmodeDocsProblemsMostCommonWordRoute
  CrackmodeDocsProblemsNumberOfGoodPairsRoute: typeof CrackmodeDocsProblemsNumberOfGoodPairsRoute
  CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute: typeof CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute
  CrackmodeDocsIntroductionIndexRoute: typeof CrackmodeDocsIntroductionIndexRoute
  CrackmodeDocsLeetcode75IndexRoute: typeof CrackmodeDocsLeetcode75IndexRoute
  CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute: typeof CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute
  CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute
  CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute
  CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute: typeof CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute
  CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute: typeof CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute
  CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute: typeof CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute
  CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute: typeof CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute
  CrackmodeDocsLeetcode75ArraysStringsIndexRoute: typeof CrackmodeDocsLeetcode75ArraysStringsIndexRoute
}

const CrackmodeDocsRouteChildren: CrackmodeDocsRouteChildren = {
  CrackmodeDocsIndexRoute: CrackmodeDocsIndexRoute,
  CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute:
    CrackmodeDocsProblemsCheckIfNumberHasEqualDigitCountAndDigitValueRoute,
  CrackmodeDocsProblemsDistributeCandiesRoute:
    CrackmodeDocsProblemsDistributeCandiesRoute,
  CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute:
    CrackmodeDocsProblemsFindAllDuplicatesInAnArrayRoute,
  CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute:
    CrackmodeDocsProblemsFindAllNumbersDisappearedInAnArrayRoute,
  CrackmodeDocsProblemsFindTheDifferenceRoute:
    CrackmodeDocsProblemsFindTheDifferenceRoute,
  CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute:
    CrackmodeDocsProblemsFindTheDifferenceOfTwoArraysRoute,
  CrackmodeDocsProblemsImplementStackUsingQueuesRoute:
    CrackmodeDocsProblemsImplementStackUsingQueuesRoute,
  CrackmodeDocsProblemsLongestConsecutiveSequenceRoute:
    CrackmodeDocsProblemsLongestConsecutiveSequenceRoute,
  CrackmodeDocsProblemsLongestPalindromeRoute:
    CrackmodeDocsProblemsLongestPalindromeRoute,
  CrackmodeDocsProblemsMissingNumberRoute:
    CrackmodeDocsProblemsMissingNumberRoute,
  CrackmodeDocsProblemsMostCommonWordRoute:
    CrackmodeDocsProblemsMostCommonWordRoute,
  CrackmodeDocsProblemsNumberOfGoodPairsRoute:
    CrackmodeDocsProblemsNumberOfGoodPairsRoute,
  CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute:
    CrackmodeDocsProblemsUniqueNumberOfOccurrencesRoute,
  CrackmodeDocsIntroductionIndexRoute: CrackmodeDocsIntroductionIndexRoute,
  CrackmodeDocsLeetcode75IndexRoute: CrackmodeDocsLeetcode75IndexRoute,
  CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute:
    CrackmodeDocsLeetcode75ArraysStringsGcdOfStringsRoute,
  CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute:
    CrackmodeDocsLeetcode75ArraysStringsIncreasingTripletSubsequenceRoute,
  CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute:
    CrackmodeDocsLeetcode75ArraysStringsIntroductionRoute,
  CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute:
    CrackmodeDocsLeetcode75ArraysStringsKidsWithGreatestCandiesRoute,
  CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute:
    CrackmodeDocsLeetcode75ArraysStringsMergeStringsAlternatelyRoute,
  CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute:
    CrackmodeDocsLeetcode75ArraysStringsProductOfArrayExceptSelfRoute,
  CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute:
    CrackmodeDocsLeetcode75ArraysStringsStringCompressionRoute,
  CrackmodeDocsLeetcode75ArraysStringsIndexRoute:
    CrackmodeDocsLeetcode75ArraysStringsIndexRoute,
}

const CrackmodeDocsRouteWithChildren = CrackmodeDocsRoute._addFileChildren(
  CrackmodeDocsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CrackmodeDocsRoute: CrackmodeDocsRouteWithChildren,
  CrackmodeIndexRoute: CrackmodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
